### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/users.txt'

### ISSUE THREAD

**Issue by dreambold** [kununu/slackdump2html#12]
```
2024/05/15 02:10:51 completed, time taken: 24.2675566s
Traceback (most recent call last):
  File "C:\Users\ddbb9\Music\slackdump2html\slackdump2html.py", line 4, in <module>
    from src.HtmlPrinter import HtmlPrinter
  File "C:\Users\ddbb9\Music\slackdump2html\src\HtmlPrinter.py", line 11, in <module>
    class HtmlPrinter:
  File "C:\Users\ddbb9\Music\slackdump2html\src\HtmlPrinter.py", line 15, in HtmlPrinter
    data_cleaner = SlackDataCleaner()
                   ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ddbb9\Music\slackdump2html\src\SlackDataCleaner.py", line 175, in __init__
    self._read_user_file()
  File "C:\Users\ddbb9\Music\slackdump2html\src\SlackDataCleaner.py", line 179, in _read_user_file
    user_file = open("data/users.txt", "r", encoding="utf-8")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/users.txt'
Press Enter to finish
```
Hello

@DerDodo Hope you are doing well!@
When I'm trying to convert the exported data to HTML, the above errors show up, where we don't have any `users.txt` in the exported files. Maybe the slackdump has bee updated? I can just see `users.json` instead.
Can you help me figure out this issue? Any input would be greatly appreciated. 

Thank you!

**Comment by dreambold** [comment]
![image](https://github.com/kununu/slackdump2html/assets/52863986/e21dbb8b-7dfa-431f-b597-166318db31ad)
This is the exported data folder, I tried to copy and rename the `users.json` file to `users.txt` but didn't work.

**Comment by dreambold** [comment]
@DerDodo I tried with the old version of slackdump, but not avail...

**Comment by dreambold** [comment]
Okay, I had to run `./export-users.sh` to make the `users.txt` file. and it worked!
But the images are not attached to the HTML file, is it an expected behavior?
